# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "STORB Consulting"
tagline: "STORB Consulting unterstützt Ihr Projekt bei Kunden und Geschäftspartnern vor Ort."
email: mail2storb@gmail.com
description: >-
  STORB Consulting unterstützt Ihr Projekt bei Kunden und Geschäftspartnern vor Ort – von der Planung über die Entwicklung bis zur Markteinführung und den Betrieb.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chstorb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: 
  name: "Christian Storb" 
  email: "mail2storb@gmail.com" 
  url: "https://chstorb.github.io/author/christian-storb/"
  avatar: "/assets/images/authors/christian-storb.jpg"
  github: "https://github.com/chstorb" 
  linkedin: "https://www.linkedin.com/in/christian-storb-326249aa/" 
  twitter: "https://twitter.com/ChristianStorb" 
  instagram: "https://www.instagram.com/storbconsulting" 
facebook:
  publisher: https://www.facebook.com/storb.christian/
github:
  username: chstorb
twitter:
  card: summary
  username: ChristianStorb   # without @
logo: "/assets/images/consulting/og-image.png"
image: "/assets/images/consulting/og-image.png"
social:
  name: Christian Storb
  links:
    - https://twitter.com/ChristianStorb
    - https://www.facebook.com/storb.christian
    - https://www.instagram.com/storbconsulting
    - https://www.linkedin.com/in/christian-storb-326249aa/
    - https://github.com/chstorb
locale: "de_DE"
lang: "de"

slugify:
  mode: pretty

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - audio

collections:
  pages:
    output: true
    permalink: /:name/
    layout: default

